name: SkWaze
author: Weefle
version: 2.1.8.1
description: The coolest addon of Skript
depends: [Skript]
softdepends: [BossBarAPI, Socket4MC, Citizens, Builder, ProtocolLib, LibsDisguises, HolographicDisplays, Netherboard, BungeeBridgeC]
main: fr.weefle.waze.Waze