name: SkWaze
author: Weefle
version: 2.1.7
description: The coolest addon of Skript
depends: [Skript]
softdepends: [BossBarAPI, Socket4MC, Citizens, Builder, ProtocolLib, LibsDisguises, HolographicDisplays]
main: fr.weefle.waze.Waze