name: SkWaze
author: Weefle
version: 2.1.4
description: The coolest addon of Skript
depends: [Skript]
softdepends: [BossBarAPI, Socket4MC, Discord-ProgramBot-API, Citizens, Builder]
main: fr.weefle.waze.Waze