name: SkWaze
author: Weefle
version: 2.1.6
description: The coolest addon of Skript
depends: [Skript]
softdepends: [BossBarAPI, Socket4MC, Discord-ProgramBot-API, Citizens, Builder, ProtocolLib, LibsDisguises]
main: fr.weefle.waze.Waze