name: SkWaze
author: Weefle
version: 2.1.9
description: The coolest addon of Skript
depends: [Skript]
softdepends: [BossBarAPI, Citizens, Builder, ProtocolLib, LibsDisguises, HolographicDisplays, Netherboard, BungeeBridgeC]
main: fr.weefle.waze.Waze